/**
 * Skill registry generator (task 6.5, 构建期生成，禁运行时动态 require).
 *
 * Scans `<repo>/video_dsl/skills/<ns>/<name>/` for skill packages
 * (SKILL.md + component.tsx + defaults.json), copies each component into
 * `src/skills/builtin/<ns>--<name>.tsx` and emits `src/skills/registry.gen.ts`
 * with STATIC imports — the Remotion bundle (webpack/rspack) does static
 * analysis, so the registry must be generated before bundling.
 *
 * Called automatically from render.ts getBundle() (and via `npm run gen:skills`).
 */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const WORKER_ROOT = path.resolve(__dirname, '..', '..');
const SKILLS_DIR = path.resolve(WORKER_ROOT, '..', 'video_dsl', 'skills');
const OUT_DIR = path.join(WORKER_ROOT, 'src', 'skills', 'builtin');
const REGISTRY_PATH = path.join(WORKER_ROOT, 'src', 'skills', 'registry.gen.ts');

export interface InstalledSkill {
  id: string;
  dir: string;
}

/** Scan the skills directory → [{id: "three/particle-wave", dir}] (fs-only). */
export function listInstalledSkills(): InstalledSkill[] {
  if (!fs.existsSync(SKILLS_DIR)) return [];
  const out: InstalledSkill[] = [];
  for (const ns of fs.readdirSync(SKILLS_DIR).sort()) {
    const nsDir = path.join(SKILLS_DIR, ns);
    if (!fs.statSync(nsDir).isDirectory()) continue;
    for (const name of fs.readdirSync(nsDir).sort()) {
      const dir = path.join(nsDir, name);
      if (
        fs.statSync(dir).isDirectory() &&
        fs.existsSync(path.join(dir, 'component.tsx'))
      ) {
        out.push({id: `${ns}/${name}`, dir});
      }
    }
  }
  return out;
}

function varNameOf(id: string): string {
  const parts = id.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  return parts.map((p) => p[0].toUpperCase() + p.slice(1)).join('');
}

function fileNameOf(id: string): string {
  return id.replace(/[^a-zA-Z0-9]+/g, '--');
}

/**
 * Copy skill components into src/skills/builtin/ and (re)generate
 * registry.gen.ts. Returns the list of registered skill ids.
 */
export function generateSkillRegistry(): string[] {
  const skills = listInstalledSkills();
  fs.mkdirSync(OUT_DIR, {recursive: true});

  const entries: Array<{id: string; varName: string; file: string; defaults: unknown}> = [];
  for (const skill of skills) {
    const file = fileNameOf(skill.id);
    fs.copyFileSync(
      path.join(skill.dir, 'component.tsx'),
      path.join(OUT_DIR, `${file}.tsx`),
    );
    let defaults: unknown = {};
    const defaultsPath = path.join(skill.dir, 'defaults.json');
    if (fs.existsSync(defaultsPath)) {
      try {
        defaults = JSON.parse(fs.readFileSync(defaultsPath, 'utf8'));
      } catch {
        defaults = {};
      }
    }
    entries.push({id: skill.id, varName: varNameOf(skill.id), file, defaults});
  }

  const lines: string[] = [
    '// AUTO-GENERATED by src/skills/generate.ts — do not edit.',
    '// Static imports only: the Remotion bundler needs static analysis.',
    'import type {ComponentType} from \'react\';',
    ...entries.map((e) => `import ${e.varName} from './builtin/${e.file}.js';`),
    '',
    'export interface SkillEntry {',
    '  // eslint-disable-next-line @typescript-eslint/no-explicit-any',
    '  Component: ComponentType<any>;',
    '  defaults: Record<string, unknown>;',
    '}',
    '',
    'export const SKILL_REGISTRY: Record<string, SkillEntry> = {',
    ...entries.map(
      (e) =>
        `  ${JSON.stringify(e.id)}: {Component: ${e.varName}, defaults: ${JSON.stringify(e.defaults)}},`,
    ),
    '};',
    '',
  ];
  fs.writeFileSync(REGISTRY_PATH, lines.join('\n'));
  return entries.map((e) => e.id);
}

/** Idempotent guard used before every bundle: (re)generate when skills changed. */
export function ensureSkillRegistry(): string[] {
  return generateSkillRegistry();
}

// CLI: `tsx src/skills/generate.ts`
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const ids = generateSkillRegistry();
  console.log(`[gen:skills] ${ids.length} skill(s): ${ids.join(', ') || '(none)'}`);
}
