// AUTO-GENERATED by src/skills/generate.ts — do not edit.
// Static imports only: the Remotion bundler needs static analysis.
import type {ComponentType} from 'react';
import ThreeFloatingShapes from './builtin/three--floating--shapes.js';
import ThreeGridTerrain from './builtin/three--grid--terrain.js';
import ThreeParticleWave from './builtin/three--particle--wave.js';

export interface SkillEntry {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  Component: ComponentType<any>;
  defaults: Record<string, unknown>;
}

export const SKILL_REGISTRY: Record<string, SkillEntry> = {
  "three/floating-shapes": {Component: ThreeFloatingShapes, defaults: {"count":12,"shape":"torus","color":"accent","speed":1}},
  "three/grid-terrain": {Component: ThreeGridTerrain, defaults: {"color":"secondary","amplitude":1,"speed":1}},
  "three/particle-wave": {Component: ThreeParticleWave, defaults: {"count":3000,"color":"primary","speed":1,"amplitude":0.6}},
};
